# Generated by Django 4.2.4 on 2023-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_treatment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='photo_treatment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
