# Generated by Django 4.2.4 on 2023-08-04 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyuser',
            name='address',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beautyuser',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
