# Generated by Django 4.2.4 on 2023-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_beautyuser_address_beautyuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyuser',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
