# Generated by Django 4.2.4 on 2023-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_beautyuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
