# Generated by Django 4.2.4 on 2023-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_beautyuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'not specified')], default=3),
        ),
    ]
