# Generated by Django 4.2.4 on 2023-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_beautyuser_bio_alter_beautyuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyuser',
            name='bio',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
