# Generated by Django 4.2.4 on 2023-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_beautyuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyuser',
            name='group',
            field=models.CharField(choices=[('practitioners', 'Practitioners'), ('clients', 'Clients'), ('admins', 'Admins')], default='clients', max_length=15),
        ),
    ]
